// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef FLCARDS_H
#define FLCARDS_H
#include <FL/Fl.H>
#include <FL/fl_ask.H>
#include "tableau.cxx"
void Quitter_CB(Fl_Widget*,void*);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Table.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
#include "pixmaps/flcards.xpm"
#include <FL/Fl_Pixmap.H>
#include <FL/Fl_Image.H>

extern Fl_Menu_Item menu_[];
#endif /* FLCARDS_H */
