// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "mainWindow.h"

int main(int argc, char **argv)
{

    mainWindow win(900, 900, "flcards");
    win.resizable(win);
	win.show(argc, argv);
    return Fl::run();
}
